### ISSUE TITLE
Show which network you are on and alert if you're not on rinkeby/main (acts as switcher too?)

### ISSUE THREAD

**Issue by johnmosesman** [ryanlabouve/forever721#41]
We can only run the snapshot on the networks we've deployed to obviously, but can we analyze any NFT? Or just rinkeby/main?

https://app.wonderland.money/#/stake

<img width="1963" alt="image" src="https://user-images.githubusercontent.com/3760568/151427934-36cf772d-e307-4e9a-8485-2b4facc5c76b.png">

**Comment by ryanlabouve** [comment]
Dup https://github.com/ryanlabouve/forever721/issues/6

**Comment by ryanlabouve** [comment]
Done via https://github.com/ryanlabouve/forever721/pull/46
